import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import AuthComponent from "./components/AuthComponent";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight:'400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ bio, children  }) {
  return (
    <html lang="en">
      {/* <head> */}
        {/* <script src="https://cdn.tailwindcss.com"></script> */}
      {/* </head> */}
      <body className={`${poppins.className} relative overflow-y-auto`}>
      <AuthComponent>
      <div className="absolute bg-transparent top-0 w-full z-20">{bio}</div>
        {children}
      </AuthComponent> 
      </body>
    </html>
  );
}
